/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.print.PrinterException;
import java.sql.DriverManager;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author MeanRegression
 */
public class shopping extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
   
    
    public shopping() {
        initComponents();
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        product1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        amount1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        product1_total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(3);
        jTextArea1.setText("Please enter the product code of the items you wish to\npurchase together with their quantity in terms of numbers");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 580, 120));

        jLabel10.setBackground(new java.awt.Color(204, 255, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("product 1");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        product1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product1ActionPerformed(evt);
            }
        });
        getContentPane().add(product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 100, -1));

        jLabel13.setBackground(new java.awt.Color(204, 255, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Quantity");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, 20));
        getContentPane().add(amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 100, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel15.setBackground(new java.awt.Color(204, 255, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("product1 total");
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        product1_total.setEditable(false);
        product1_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product1_totalActionPerformed(evt);
            }
        });
        getContentPane().add(product1_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, -1));

        receipt.setEditable(false);
        receipt.setColumns(20);
        receipt.setRows(5);
        jScrollPane2.setViewportView(receipt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 350, 250));

        jButton3.setBackground(new java.awt.Color(51, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("BUY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        jButton5.setBackground(new java.awt.Color(51, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("SECURITY");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 423, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void shop(){
     String q;
     int a;
     
     String p;
     int m;
     if(!(product1.getText().isEmpty()||amount1.getText().isEmpty())){
             
         try {
            String querry="SELECT `product_code`, `product_name`, `price`, `amount` FROM `product` WHERE `product_code`=?";
            conn=DriverManager.getConnection("jdbc:mysql://localhost/patoh","root","");
            pst=conn.prepareStatement(querry);
            
             pst.setString(1, product1.getText());
            
            rs=pst.executeQuery();
           
           if(rs.next()){
            p=rs.getString("product_name");
            m=rs.getInt("price");
         int h=rs.getInt("Amount");
              
            q=amount1.getText();
            
            
            a=Integer.parseInt(q);
            int total=m*a;
            
            if(h<a){
                JOptionPane.showMessageDialog(null, "Not enough stock!! " + "" + "Stock is " + "" + h);
            }
            else{
                String sql1="select * from account where username=?";
             
             pst=conn.prepareStatement(sql1);
             pst.setString(1,login1.username);
             rs=pst.executeQuery();
             if (rs.next()){
               int  balance=rs.getInt("balance");
               if(total>balance){
                   JOptionPane.showMessageDialog(null, "not enough money " + " " + " balance is " + " " + balance);
               }
               else{
            total=a*m;
            product1_total.setText(String.valueOf(total));
            String db="SELECT * FROM `sales` WHERE `product_code`=?";
            pst=conn.prepareStatement(db);
            pst.setString(1, product1.getText());
            rs=pst.executeQuery();
           
            if(rs.next()){
                int s=rs.getInt("Amount");
                int a2=a+s;
                String jaribu="UPDATE `sales` SET `Amount`=? WHERE `product_code`=?";
                 pst=conn.prepareStatement(jaribu);
                 pst.setInt(1, a2);
                  pst.setString(2, product1.getText());
                  pst.executeUpdate();
                  
                  String sql3="INSERT INTO `monitor`(`username`, `product_code`, "
                          + "`product_name`, `price`, `amount`,total_amount) VALUES (?,?,?,?,?,?)";
                  pst=conn.prepareStatement(sql3);
                  pst.setString(1, login1.username);
                  pst.setString(2, product1.getText());
                  pst.setString(3, p);
                  pst.setInt(4, m);
                  pst.setInt(5, a);
                  pst.setInt(6, total);
                  pst.executeUpdate();
                  
                  String sql5="select points from monitor where username=?";
                  pst=conn.prepareStatement(sql5);
                  pst.setString(1, login1.username);
                  rs=pst.executeQuery();
                  if(rs.next()){
                  int point=rs.getInt("points");
                  String sql4="UPDATE `monitor` SET `points`=? WHERE username=?;";
                      pst=conn.prepareStatement(sql4);
                  if(total<100){
                      int points=1+point;
                      
                      pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                    
                  }
                  else if(total>=100&&total<200){
                      int points=5+point;
                     
                      pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                  }
                  else if(total>=200&&total<500){
                      int points=10+point;
                       pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                  }
                  else if(total>=500&&total<1000){
                      int points=15+point;
                       pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                  }
                  else{
                      int points=20+point;
                       pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                  }}
                  String updator="UPDATE `sales` SET `amount2`= ? WHERE `product_code`=?";
                  pst=conn.prepareStatement(updator);
                  pst.setInt(1, a);
                  pst.setString(2, product1.getText());
                  pst.executeUpdate();
                  
                  String delete="UPDATE `sales` SET `amount2`=0 WHERE product_code=?";
                   pst=conn.prepareStatement(delete);
                   pst.setString(1, product1.getText());
                  pst.executeUpdate();
            }
            else{
            String sql="INSERT INTO `sales`(`product_code`, `product_name`, `price`, `Amount`)"
                    + " VALUES (?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, product1.getText());
            pst.setString(2, p);
            pst.setInt(3, m);
            pst.setInt(4, a);
            
            pst.executeUpdate();
            String sql3="INSERT INTO `monitor`(`username`, `product_code`, "
                          + "`product_name`, `price`, `amount`,total_amount) VALUES (?,?,?,?,?,?)";
                  pst=conn.prepareStatement(sql3);
                  pst.setString(1, login1.username);
                  pst.setString(2, product1.getText());
                  pst.setString(3, p);
                  pst.setInt(4, m);
                  pst.setInt(5, a);
                  pst.setInt(6, total);
                  pst.executeUpdate();
                  
                  String sql5="select points from monitor where username=?";
                  pst=conn.prepareStatement(sql5);
                  pst.setString(1, login1.username);
                  rs=pst.executeQuery();
                  if(rs.next()){
                  int point=rs.getInt("points");
                  String sql4="UPDATE `monitor` SET `points`=? WHERE username=?;";
                      pst=conn.prepareStatement(sql4);
                  if(total<100){
                      int points=1+point;
                      
                      pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                    
                  }
                  else if(total>=100&&total<200){
                      int points=5+point;
                     
                      pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                  }
                  else if(total>=200&&total<500){
                      int points=10+point;
                       pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                  }
                  else if(total>=500&&total<1000){
                      int points=15+point;
                       pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                  }
                  else{
                      int points=20+point;
                       pst.setInt(1, points);
                      pst.setString(2, login1.username);
                      pst.executeUpdate();
                  }}
            }
            receipt.append(
                    "\t"+"THANKS FOR CHOOSING US" +"\n"+
                    "===============================================\n" +
                    "PRO_NAME"+"\t"+"ITEMS"+"\t"+"PRICE"+"\t"+"TOTAL\n"+
                    "-------------------------------------------------------------------------------\n" 
                    +p+"\t"+amount1.getText()+"\t"+m+"\t"+product1_total.getText()+"\n"+
                     "===============================================\n"+ 
                     "THANKS FOR SHOPPING AND WELCOME AGAIN!!!"
            
            
            );
             
            
        }}}}
        else{
                    JOptionPane.showMessageDialog(null,"Can't find item in database,please check the product code and try again" );
                } }  catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex);
        }}}
    private void product1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        main main=new main();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void product1_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product1_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product1_totalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
       
        shop();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            receipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(shopping.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        product1.setText("");
       
        amount1.setText("");
        
        product1_total.setText("");
        
        receipt.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        security sec=new security();
        sec.setVisible(true);
        sec.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField product1;
    private javax.swing.JTextField product1_total;
    private javax.swing.JTextArea receipt;
    // End of variables declaration//GEN-END:variables
}
